### ISSUE TITLE
Footer section - previews

### ISSUE THREAD

**Issue by stevieflow** [notshi/d-preview#11]
We have a big bunch of info and links that are not applicable to the ringfenced world of the preview:

![d-portal (49)](https://user-images.githubusercontent.com/1209944/108888877-a62eda80-7603-11eb-8da6-1366187a9f82.png)

is there any way to chop this out..?

**Comment by stevieflow** [comment]
There also this text above the footer:

![d-portal (50)](https://user-images.githubusercontent.com/1209944/108889141-eee69380-7603-11eb-8fcb-0782cd563785.png)

Again - I think remove this , so not to confuse people

The whole footer could be replace by the text at https://github.com/notshi/portald/issues/10

**Comment by notshi** [comment]
Due to the nature of the website, the data description section is bespoke.
There are currently 23 different pages with different descriptions which had to be replaced so this was a major change to the d-portal framework as it meant deleting foundational sections of the website and re-organising the layout of the site as a repercussion.

The changes are now live but there could be teething issues.

Hopefully, things are still standing and the website hasn't fallen over but please let us know otherwise.

**Comment by stevieflow** [comment]
Amazing - thanks!
